Table Cliente {
    id_cliente int [PK]
    nombre_cliente varchar
    Apellido varchar
    Documento varchar [UNIQUE]
    Direccion varchar
    Telefono varchar

}
Table Plan {
    id_plan int [PK]
    nombre_plan varchar
    tipo_plan varchar
    precio_mensual decimal(10,2)
    velocidad int
}

Table Contrato {
    id_contrato int [PK]
    id_cliente int [FK]
    id_plan int [FK]
    fecha_inicio Date 
    fecha_fin Date
    estado_contrato varchar
}

Table Factura {
    id_factura int [PK]
    id_contrato int [FK]
    fecha_emision Date 
    fecha_vencimiento Date
    monto_total decimal(10,2)
    estado_factura varchar
}

 
Table Pago {
    id_pago int [PK]
    id_factura int [FK]
    fecha_pago Date 
    monto_pagado decimal(10,2)
    metodo_pago varchar
}

 REF: Cliente.id_cliente < Contrato.id_cliente
 REF: Plan.id_plan > Contrato.id_plan
 REF: Contrato.id_contrato < Factura.id_contrato
 REF: Factura.id_factura < Pago.id_factura

 
