Table Cliente {
    id_cliente int [PK]
    nombre_cliente varchar
    Apellido varchar
    Documento varchar [UNIQUE]
    Direccion varchar
    Telefono varchar

}
Table Plan {
    id_plan int [PK]
    nombre_plan varchar
    Tipo_plan varchar
    Precio_mensual decimal(10,2)
    Velocidad int
}

Table Contrato {
    id_contrato int [PK]
    id_cliente int
    id_plan int [FK]
    Fecha_inicio Date 
    Fecha_fin Date
    Estado varchar
}

Table Factura {
    id_factura int [PK]
    id_contrato int [FK]
    Fecha_emision Date 
    Fecha_vencimiento Date
    Monto_total decimal(10,2)
    Estado varchar
}

 
Table Pago {
    id_pago int [PK]
    id_factura int [FK]
    Fecha_pago Date 
    Monto_pagado decimal(10,2)
    Metodo_pago varchar
}

 REF: Cliente.id_cliente < Contrato.id_cliente
 REF: Plan.id_plan > Contrato.id_plan
 REF: Contrato.id_contrato < Factura.id_contrato
 REF: Factura.id_factura < Pago.id_factura

 
